### ISSUE TITLE
Wie kann per Cronjob die GEDCOM-Datei in bestimmten Ordner gespeichert werden?

### ISSUE THREAD

**Issue by WeT-Klb** [Jefferson49/DownloadGedcomWithURL#5]
Hallo,

ich habe das Modul installiert und kann es auch konfigurieren. Ich habe dann einen GEDCOM-Ordner im Stammverzeichnis von webtrees angelegt und als Ziel für die Automatik festgelegt. In meiner Cronjob-Liste habe ich folgenden Eintrag hinzugefügt:

wget --timeout=60 --tries=1 "https://DOMAINNAME/webtrees/index.php?route=/webtrees/DownloadGedcomWithURL&tree=tree1&key=XXXXXXXX&file=export&privacy=user&key=XXXXXXXX"

Wenn ich den https-Teil im Webbrowser aufrufe, wird die ged-Datei heruntergeladen. Was muss ich in dem obigen Befehl ändern, damit der Cronjob die Datei in den Ordner "webtrees/GEDCOM" ablegt? Ich muss zugeben, dass ich meine Probleme mit der Erklärung der Befehle/Optionen habe.

Hello,

i installed the module and i can also configure it. I then created a GEDCOM folder in the root of webtrees and set it as the target for the automatic. In my cronjob list i added the following entry:

wget --timeout=60 --tries=1 "https://DOMAINNAME/webtrees/index.php?route=/webtrees/DownloadGedcomWithURL&tree=tree1&key=XXXXXXXX&file=export&privacy=user&key=XXXXXXXX"

When I call the https part in the web browser, the ged file is downloaded. What do I need to change in the above command to make the cronjob put the file in the "webtrees/GEDCOM" folder? I must admit that I have my problems with the explanation of the commands/options.

![Pic1](https://user-images.githubusercontent.com/20600342/230762899-6872f9a2-802d-4adc-90f1-e023c5e73459.jpg)
![Pic2](https://user-images.githubusercontent.com/20600342/230762903-15194b2d-d3e1-41f2-a5d3-9104d7568b82.jpg)

**Comment by Jefferson49** [comment]
Hallo, 

zum Abspeichern der GEDCOM Datei auf dem Server muss man **&action=save** an die URL anhängen, also:

`wget --timeout=60 --tries=1 "https://domainname/webtrees/index.php?route=/webtrees/DownloadGedcomWithURL&tree=tree1&file=export&privacy=user&key=XXXXXXXX&action=save"
`

Noch ein Hinweis: im beigefügten Beispiel-Script habe ich versehentlich den Key zweimal in die URL eingefügt (&key=XXXXXXXX). Einmal genügt aber; zweimal schadet aber auch nicht. Habe einen der Keys im obigen wget-Aufruf gelöscht.

Bei weiteren Fragen gerne nochmal melden.

**Comment by WeT-Klb** [comment]
Vielen hezlichen Dank für die schnelle Antwort - gleich getestet und funktioniert.
Worin besteht eigentlich der Unterschied zwischen privacy=user und privacy=gedadmin in Bezug auf die GEDCOM-Datei?
Was unterscheidet beide Versionen?

**Comment by Jefferson49** [comment]
Die Werte entsprechen den Eingabe-Möglichkeiten aus der Eingabemaske in der Verwaltung:

- Verwalter: gedadmin
- Mitglied: user
- Besucher: visitor
- Keine: none

![Gedcom Export](https://user-images.githubusercontent.com/81484983/230765292-a4107642-2f32-4a73-beca-164e97885da4.JPG)

**Comment by Jefferson49** [comment]
Da es mit den URL Parametern schon etwas kompliziert ist, überlege ich mir vielleicht für eine weitere Version, die Parameter in der Konfiguration einstellbar zu machen. Dann wäre es vmtl. besser verständlich. Eine Idee wäre, dass diese Konfiguration gilt, solange keine anderen Parameter in der URL übergeben werden. Letzteres will ich weiter ermöglichen, weil es viel Flexibilität beim Scripting bietet bzw. in jedem Script ggfs. eine andere Auswahl getroffen werden kann.

**Comment by Jefferson49** [comment]
> Worin besteht eigentlich der Unterschied zwischen privacy=user und privacy=gedadmin in Bezug auf die GEDCOM-Datei?
> Was unterscheidet beide Versionen?

Man kann die Rechte für die einzelnen Rollen unter "Verwaltung / Stammbäume verwalten / Datenschutz" einstellen. Dort kann man Rechte bezogen auf die genannten Rollen einstellen. Weiterhin werden die RESN Tags aus der GEDCOM-Datei bzw. die "Einschränkungen", die man im webtrees Frontend für bestimmte Daten einstellt, berücksichtigt.

**Comment by WeT-Klb** [comment]
Ah - ok.
Letzte Fragen: 
1. Wie definiere ich, welche der beiden ZIP-Versionen (ZIP oder ZIP mit Mediadateien) ich sichern will.
2. Bei z.B. täglicher Sicherung - wird der Dateiname mit (1), (2) usw erweitert oder wird die bestehende ged-Datei überschrieben?

Das Problem mit den Optionen ist gar nicht so groß, nur muß man erstmal die Syntax verstehen.
Ich habe z.B. immer nach "MY_*" gesucht - weil Du ja in der README.md die Optionen mit z.B. MY_TREE, MY_KEY usw. erläuterst.
Darüber erklärst Du das URL-Format ebenso - die "Example URLs" haben aber nur am Anfang das "MY_URL" und dann aber den "richtigen" Aufruf.
Ich wusste jetzt nicht, wann der Zusatz "MY_*" verwendet werden muß.

**Comment by Jefferson49** [comment]
> Bei z.B. täglicher Sicherung - wird der Dateiname mit (1), (2) usw erweitert oder wird die bestehende ged-Datei überschrieben?

Ja, wenn Du nichts weiter unternimmst wird immer der gleiche Datei-Name generiert und die Datei wird überschrieben. 

Du kannst aber mit **&time_stamp=prefix** oder **&time_stamp=postfix** einen Zeitstempel mit der GMT-Zeit an den Dateinamen anhängen lassen. Dann wird die Datei jedes Mal mit einem entsprechenden Dateinamen abgespeichert und nicht überschrieben.

Eine weitere Möglichkeit ist, dass Du den Datei-Namen in der URL mit Deinem Skript selbst generierst/modifiziert. Der Dateinamen, welcher für das Abspeichern genutzt wird, kann über **&file=...** eingestellt werden.

**Comment by Jefferson49** [comment]
> _Ich wusste jetzt nicht, wann der Zusatz "MY__" verwendet werden muß.

o.k., ist etwas verwirrend. Ich muss mir den Text für das Readme File nochmal anschauen.

**Comment by WeT-Klb** [comment]
> Ja, wenn Du nichts weiter unternimmst wird immer der gleiche Datei-Name generiert und die Datei wird überschrieben.

Das ist genau mein Vorhaben! Vielen lieben Dank für Deine Unterstützung.
